
web:
  image: 'gitlab/gitlab-ee:latest'
  restart: always
  hostname: '10.250.14.1'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://10.250.14.1:8929'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
      registry_external_url 'http://10.250.14.1:5050'
  ports:
    - '8929:8929'
    - '2224:22'
    - '5050:5050'
  volumes:
    - '$GITLAB_HOME/config:/etc/gitlab'
    - '$GITLAB_HOME/logs:/var/log/gitlab'
    - '$GITLAB_HOME/data:/var/opt/gitlab'
